# Generated by Django 3.0.5 on 2020-05-18 11:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('criteria_name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Имя критерия')),
                ('criteria_value', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Вес критерия')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictName', models.CharField(max_length=240)),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('main_estim', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='DictObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50, verbose_name='Имя критерия')),
                ('value', models.CharField(choices=[('0', 0), ('0.25', 0.25), ('0.5', 0.5), ('0.75', 0.75), ('1.0', 1.0)], default=0, max_length=10, verbose_name='Уровень владения')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.Dict')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.Criteria', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.AddField(
            model_name='dict',
            name='spec',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specialists.Specialist'),
        ),
    ]
