# Generated by Django 3.0.4 on 2020-04-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_sperm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='dick',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specialists.Specialist'),
        ),
        migrations.DeleteModel(
            name='Testling',
        ),
    ]
