# Generated by Django 3.0.4 on 2020-04-25 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_auto_20200425_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='dick',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specialists.Dick'),
        ),
    ]
