# Generated by Django 3.0.4 on 2020-04-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0006_auto_20200425_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dick',
        ),
    ]
