# Generated by Django 3.0.4 on 2020-04-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0008_auto_20200425_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dict',
            old_name='dick',
            new_name='spec',
        ),
    ]
