# Generated by Django 3.0.4 on 2020-04-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0010_auto_20200425_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dict',
            old_name='name',
            new_name='dictName',
        ),
    ]
