# Generated by Django 3.0.4 on 2020-04-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_balls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sperm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=240)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.Balls')),
            ],
        ),
    ]
