# Generated by Django 3.0.4 on 2020-04-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0009_auto_20200425_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict',
            options={'verbose_name': 'Словарь', 'verbose_name_plural': 'Словари'},
        ),
        migrations.AlterModelOptions(
            name='dictobj',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
    ]
