# Generated by Django 3.0.5 on 2020-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0011_auto_20200427_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='main_estim',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
