# Generated by Django 3.0.5 on 2020-05-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0014_auto_20200512_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estim',
        ),
    ]
